#ddev-generated
webimage_extra_packages: [ssh]
web_extra_daemons:
  - name: "ssh"
    command: "sudo /usr/sbin/sshd -D"
    directory: "/run/sshd"
hooks:
  post-start:
    - exec: ssh-add -L 2>&1 > /dev/null && ssh-add -L >> ~/.ssh/authorized_keys
